### ISSUE TITLE
Roctracer returns CopyHostToDevice for hipMemcpyDtoD API call. 

### ISSUE THREAD

**Issue by reza-amd** [ROCm/roctracer#53]
Please look at the attached image. At HIP API activity record, we have executed hipMemcpyDtoD  but in ACTIVITY_DOMAIN_HIP_OPS it shows a CopyHostToDevice (kind = 4596).
![Capture](https://user-images.githubusercontent.com/79117684/114290413-72353a80-9a34-11eb-8ffc-8988e31b6af1.PNG)
Please ignore the invalid device id and stream id in the second line.

**Comment by reza-amd** [comment]
Here is the codes to reproduce this issue.
Please run "make run" after extracting the zip file.

[roctracer_issue.zip](https://github.com/ROCm-Developer-Tools/roctracer/files/6301448/roctracer_issue.zip)

**Comment by ppanchad-amd** [comment]
@reza-amd Can you please check if issue still occurs with the latest ROCm 6.2. Thanks!

**Comment by tcgu-amd** [comment]
@reza-amd Sorry for the lack of response. We are not able to reproduce the issue on latest rocm 6.2
![image](https://github.com/user-attachments/assets/b9e0283f-e49e-474b-985f-2e6205adf5f6)

Seems like the CopyHostToDevices was supposed to belong to the hipMemcpy command for host to device operation (sample.cc line 100) that was not reported in older versions of hip runtime. 

We will close the ticket since the issue seem to no longer exist in the newest version of ROCm & is not a breaking error. Please feel free to reopen/follow up if you think it requires further address. Thanks!
